// Given two strings s and t which consist of only lowercase letters.

// String t is generated by random shuffling string s and then add one more letter at a random position.

// Find the letter that was added in t.

// Example:

// Input:
// s = "abcd"
// t = "abcde"

// Output:
// e

// Explanation:
// 'e' is the letter that was added.

/**
 * @param {string} s
 * @param {string} t
 * @return {character}
 */
var findTheDifference1 = function(s, t) {
    let sum = 0,
        sumt = 0;
    for(let i=0, l=s.length; i<l; i++){
        sum+=s.charCodeAt(i);
        sumt+=t.charCodeAt(i);
    }
    sumt += t[t.length-1].charCodeAt(0);
    return String.fromCharCode(sumt - sum );
};

var findTheDifference = function(s, t){
     //convert char to num, since xor operator will cast char to num
    let c = t.charCodeAt(t.length-1);           
    for(let i=0; i < s.length; i++){
        c = c ^ s.charCodeAt(i) ^ t.charCodeAt(i);
    }
    return String.fromCharCode(c);
};

console.log(findTheDifference('a', 'aa'));